<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 17/10/16
 * Time: 4:18 PM
 */
class Achievement extends DataObject
{
    private static $db = array(
        'Date' => 'Date',
        'AchievementText' => 'Text',
        'Type'  =>  'Varchar(20)'
    );

    private static $summary_fields = array(
        'Date' => 'Date',
        'AchievementText' => 'AchievementText'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->addFieldToTab('Root.Main', DateField::create('Date', 'Date Achieved')
            ->setConfig('dateformat', 'dd-MM-yyyy')
            ->setConfig('showcalendar', true));
        $fields->addFieldToTab('Root.Main', new DropdownField(
            'Type',
            'Choose an achievement type',
            AchievementType::get()->map('ID', 'Title')->toArray(),
            null,
            true
        ), 'AchievementText');
        return $fields; // TODO: Change the autogenerated stub
    }

    public function AchievementYear()
    {
        $formatDate = date("Y", strtotime($this->Date));
        return $formatDate;
    }

}
