<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 17/10/16
 * Time: 4:18 PM
 */
class Achievement extends DataObject
{
    private static $db = array(
        'Date' => 'Date',
        'AchievementText' => 'Text'
    );

    private static $summary_fields = array(
        'Date' => 'Date',
        'AchievementText' => 'AchievementText'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        return $fields; // TODO: Change the autogenerated stub
    }

}
