<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 17/10/16
 * Time: 4:32 PM
 */
class Reference extends DataObject
{
    private static $db = array(
        'Name' => 'Text',
        'Position' => 'Text',
        'Phone' => 'Text',
        'Email' => 'Text',
        'Rating' => "Enum('1,2,3,4,5,6,7,8,9,10', '1')"
    );

    private static $summary_fields = array(
        'Name' => 'Name',
        'Position' => 'Position',
        'Phone' => 'Phone',
        'Email' => 'Email',
        'Rating' => 'Rating'

    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        return $fields; // TODO: Change the autogenerated stub
    }
}
