<?php

use SilverStripe\Forms\DropdownField;
use SilverStripe\ORM\DataObject;
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 17/10/16
 * Time: 1:44 PM
 */
class Subject extends DataObject
{
    private static $db = array(
        'Title' => 'Text',
        'APoint' => 'Int',
        'MPoint' => 'Int',
        'EPoint' => 'Int',
        'Teacher' => 'Text',
        'Comment' => 'Text',
        'ReportType' => 'Text'
    );

    private static $has_one = array(
        'EducationPage' => 'EducationPage'
    );

    private static $summary_fields = array(
        'Title' => 'Title',
        'APoint' => 'Achievements',
        'MPoint' => 'Merits',
        'EPoint' => 'Excellence',
        'Teacher' => 'Teacher',
        'ReportType' => 'ReportType'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->addFieldToTab('Root.Main', new DropdownField(
            'Teacher',
            'Choose A Teacher',
            Teacher::get()->map('ID', 'Name')->toArray(),
            null,
            true
        ), 'APoint');

        return $fields; // TODO: Change the autogenerated stub
    }

    /**
     * @param string $teacherName
     * @return Teacher->Name
     */
    public function getTeacherName($teacherName = '')
    {
        $teacher = Teacher::get()->filter(array(
            'ID' => $this->Teacher
        ));
        foreach ($teacher as $t)
        {
            $teacherName = $t->Name;
        }
        return $teacherName;
    }

}
