<?php

use SilverStripe\ORM\DataObject;
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 17/10/16
 * Time: 2:16 PM
 */
class Teacher extends DataObject
{
    private static $db = array(
        'Name' => 'Text',
        'Phone' => 'Varchar(20)',
        'Email' => 'Varchar(60)'
    );

    private static $summary_fields = array(
        'Name' => 'Name',
        'Phone' => 'Phone',
        'Email' => 'Email'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        return $fields; // TODO: Change the autogenerated stub
    }
}
